=head1 NAME

dis89 - Disassemble programs for the Intel 8089 I/O processor

=head1 SYNOPSIS

=over 4

=item B<dis89> [<I<iop.bin>>]

=back

=head1 DESCRIPTION

B<dis89> it translates the binary dumps of Intel 8089 programs
into a pretty textural format. The output is human readable
and hopefully requires very few modifications in order to be
compiled back to the binary form.

It serves as an example of how to use I<lib8089>. As such, it
aims to be simple and therefore doesn't do anything particularly
clever (such as generating symbolic labels for jump targets)
nor does it provide any means to configure and customize the
output.

If you're looking for a more advanced 8089 disassembler,
or an assembler check out B<disi89> (or B<asi89>) from
L<https://github.com/brouhaha/i89>.

=head1 BUGS

Would you expect any in a C program that parses complex data and
was mostly written under influence?

=head1 AUTHORS

=over

=item * Lubomir Rintel <L<lkundrak@v3.sk>>

=back

Nobody else helped me.

This program is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 2 of the License, or (at your
option) any later version.

The source code repository can be obtained from
L<https://github.com/lkundrak/lib8089>. Bug fixes and feature
ehancements licensed under same conditions as lib8089 are welcome
via GIT pull requests.
